// ============================================================
//  BOOKING STATUS CONSTANTS
//  src/common/constants/bookingStatus.js
// ============================================================

const BOOKING_STATUS = {
  PENDING: "pending",
  CONFIRMED: "confirmed",
  PROCESSING: "processing",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
  REFUNDED: "refunded",
  PARTIALLY_REFUNDED: "partially_refunded",
  FAILED: "failed",
  EXPIRED: "expired",
  WAITLIST: "waitlist",
  RESERVED: "reserved",
};

const BOOKING_STATUS_LABELS = {
  [BOOKING_STATUS.PENDING]: "Pending Confirmation",
  [BOOKING_STATUS.CONFIRMED]: "Confirmed",
  [BOOKING_STATUS.PROCESSING]: "Processing",
  [BOOKING_STATUS.COMPLETED]: "Completed",
  [BOOKING_STATUS.CANCELLED]: "Cancelled",
  [BOOKING_STATUS.REFUNDED]: "Refunded",
  [BOOKING_STATUS.PARTIALLY_REFUNDED]: "Partially Refunded",
  [BOOKING_STATUS.FAILED]: "Failed",
  [BOOKING_STATUS.EXPIRED]: "Expired",
  [BOOKING_STATUS.WAITLIST]: "Waitlist",
  [BOOKING_STATUS.RESERVED]: "Reserved",
};

const BOOKING_STATUS_COLORS = {
  [BOOKING_STATUS.PENDING]: "warning",
  [BOOKING_STATUS.CONFIRMED]: "success",
  [BOOKING_STATUS.PROCESSING]: "info",
  [BOOKING_STATUS.COMPLETED]: "success",
  [BOOKING_STATUS.CANCELLED]: "error",
  [BOOKING_STATUS.REFUNDED]: "default",
  [BOOKING_STATUS.PARTIALLY_REFUNDED]: "default",
  [BOOKING_STATUS.FAILED]: "error",
  [BOOKING_STATUS.EXPIRED]: "default",
  [BOOKING_STATUS.WAITLIST]: "warning",
  [BOOKING_STATUS.RESERVED]: "info",
};

const BOOKING_STATUS_TRANSITIONS = {
  [BOOKING_STATUS.PENDING]: [
    BOOKING_STATUS.CONFIRMED,
    BOOKING_STATUS.CANCELLED,
    BOOKING_STATUS.EXPIRED,
    BOOKING_STATUS.FAILED,
  ],
  [BOOKING_STATUS.CONFIRMED]: [
    BOOKING_STATUS.COMPLETED,
    BOOKING_STATUS.CANCELLED,
    BOOKING_STATUS.REFUNDED,
  ],
  [BOOKING_STATUS.PROCESSING]: [
    BOOKING_STATUS.CONFIRMED,
    BOOKING_STATUS.FAILED,
  ],
  [BOOKING_STATUS.COMPLETED]: [BOOKING_STATUS.REFUNDED],
  [BOOKING_STATUS.CANCELLED]: [],
  [BOOKING_STATUS.REFUNDED]: [],
  [BOOKING_STATUS.PARTIALLY_REFUNDED]: [BOOKING_STATUS.REFUNDED],
  [BOOKING_STATUS.FAILED]: [BOOKING_STATUS.PENDING],
  [BOOKING_STATUS.EXPIRED]: [BOOKING_STATUS.PENDING],
  [BOOKING_STATUS.WAITLIST]: [BOOKING_STATUS.PENDING, BOOKING_STATUS.CANCELLED],
  [BOOKING_STATUS.RESERVED]: [BOOKING_STATUS.CONFIRMED, BOOKING_STATUS.EXPIRED],
};

const BOOKING_STATUS_PRIORITY = {
  [BOOKING_STATUS.PENDING]: 1,
  [BOOKING_STATUS.RESERVED]: 2,
  [BOOKING_STATUS.PROCESSING]: 3,
  [BOOKING_STATUS.CONFIRMED]: 4,
  [BOOKING_STATUS.COMPLETED]: 5,
  [BOOKING_STATUS.WAITLIST]: 6,
  [BOOKING_STATUS.CANCELLED]: 7,
  [BOOKING_STATUS.REFUNDED]: 8,
  [BOOKING_STATUS.PARTIALLY_REFUNDED]: 9,
  [BOOKING_STATUS.FAILED]: 10,
  [BOOKING_STATUS.EXPIRED]: 11,
};

const ACTIVE_BOOKING_STATUSES = [
  BOOKING_STATUS.PENDING,
  BOOKING_STATUS.CONFIRMED,
  BOOKING_STATUS.PROCESSING,
  BOOKING_STATUS.RESERVED,
];

const COMPLETED_BOOKING_STATUSES = [
  BOOKING_STATUS.COMPLETED,
  BOOKING_STATUS.CANCELLED,
  BOOKING_STATUS.REFUNDED,
  BOOKING_STATUS.PARTIALLY_REFUNDED,
  BOOKING_STATUS.FAILED,
  BOOKING_STATUS.EXPIRED,
];

const CANCELLABLE_STATUSES = [
  BOOKING_STATUS.PENDING,
  BOOKING_STATUS.CONFIRMED,
  BOOKING_STATUS.RESERVED,
];

const REFUNDABLE_STATUSES = [
  BOOKING_STATUS.CONFIRMED,
  BOOKING_STATUS.COMPLETED,
];

module.exports = {
  BOOKING_STATUS,
  BOOKING_STATUS_LABELS,
  BOOKING_STATUS_COLORS,
  BOOKING_STATUS_TRANSITIONS,
  BOOKING_STATUS_PRIORITY,
  ACTIVE_BOOKING_STATUSES,
  COMPLETED_BOOKING_STATUSES,
  CANCELLABLE_STATUSES,
  REFUNDABLE_STATUSES,
};
