// ============================================================
//  EVENT STATUS CONSTANTS
//  src/common/constants/eventStatus.js
// ============================================================

const EVENT_STATUS = {
  DRAFT: "draft",
  PENDING: "pending",
  PUBLISHED: "published",
  ONGOING: "ongoing",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
  POSTPONED: "postponed",
  RESCHEDULED: "rescheduled",
  SOLD_OUT: "sold_out",
  ARCHIVED: "archived",
  REJECTED: "rejected",
  UNDER_REVIEW: "under_review",
};

const EVENT_STATUS_LABELS = {
  [EVENT_STATUS.DRAFT]: "Draft",
  [EVENT_STATUS.PENDING]: "Pending Approval",
  [EVENT_STATUS.PUBLISHED]: "Published",
  [EVENT_STATUS.ONGOING]: "Ongoing",
  [EVENT_STATUS.COMPLETED]: "Completed",
  [EVENT_STATUS.CANCELLED]: "Cancelled",
  [EVENT_STATUS.POSTPONED]: "Postponed",
  [EVENT_STATUS.RESCHEDULED]: "Rescheduled",
  [EVENT_STATUS.SOLD_OUT]: "Sold Out",
  [EVENT_STATUS.ARCHIVED]: "Archived",
  [EVENT_STATUS.REJECTED]: "Rejected",
  [EVENT_STATUS.UNDER_REVIEW]: "Under Review",
};

const EVENT_STATUS_COLORS = {
  [EVENT_STATUS.DRAFT]: "default",
  [EVENT_STATUS.PENDING]: "warning",
  [EVENT_STATUS.PUBLISHED]: "success",
  [EVENT_STATUS.ONGOING]: "info",
  [EVENT_STATUS.COMPLETED]: "success",
  [EVENT_STATUS.CANCELLED]: "error",
  [EVENT_STATUS.POSTPONED]: "warning",
  [EVENT_STATUS.RESCHEDULED]: "info",
  [EVENT_STATUS.SOLD_OUT]: "error",
  [EVENT_STATUS.ARCHIVED]: "default",
  [EVENT_STATUS.REJECTED]: "error",
  [EVENT_STATUS.UNDER_REVIEW]: "warning",
};

const EVENT_STATUS_TRANSITIONS = {
  [EVENT_STATUS.DRAFT]: [EVENT_STATUS.PENDING, EVENT_STATUS.ARCHIVED],
  [EVENT_STATUS.PENDING]: [
    EVENT_STATUS.PUBLISHED,
    EVENT_STATUS.REJECTED,
    EVENT_STATUS.UNDER_REVIEW,
  ],
  [EVENT_STATUS.PUBLISHED]: [
    EVENT_STATUS.ONGOING,
    EVENT_STATUS.CANCELLED,
    EVENT_STATUS.POSTPONED,
    EVENT_STATUS.SOLD_OUT,
  ],
  [EVENT_STATUS.ONGOING]: [EVENT_STATUS.COMPLETED, EVENT_STATUS.CANCELLED],
  [EVENT_STATUS.COMPLETED]: [EVENT_STATUS.ARCHIVED],
  [EVENT_STATUS.CANCELLED]: [],
  [EVENT_STATUS.POSTPONED]: [EVENT_STATUS.PUBLISHED, EVENT_STATUS.RESCHEDULED],
  [EVENT_STATUS.RESCHEDULED]: [EVENT_STATUS.PUBLISHED],
  [EVENT_STATUS.SOLD_OUT]: [EVENT_STATUS.PUBLISHED],
  [EVENT_STATUS.ARCHIVED]: [],
  [EVENT_STATUS.REJECTED]: [EVENT_STATUS.DRAFT, EVENT_STATUS.ARCHIVED],
  [EVENT_STATUS.UNDER_REVIEW]: [EVENT_STATUS.PUBLISHED, EVENT_STATUS.REJECTED],
};

const PUBLIC_EVENT_STATUSES = [
  EVENT_STATUS.PUBLISHED,
  EVENT_STATUS.ONGOING,
  EVENT_STATUS.SOLD_OUT,
];

const ACTIVE_EVENT_STATUSES = [EVENT_STATUS.PUBLISHED, EVENT_STATUS.ONGOING];

const MODIFIABLE_EVENT_STATUSES = [
  EVENT_STATUS.DRAFT,
  EVENT_STATUS.PENDING,
  EVENT_STATUS.UNDER_REVIEW,
];

module.exports = {
  EVENT_STATUS,
  EVENT_STATUS_LABELS,
  EVENT_STATUS_COLORS,
  EVENT_STATUS_TRANSITIONS,
  PUBLIC_EVENT_STATUSES,
  ACTIVE_EVENT_STATUSES,
  MODIFIABLE_EVENT_STATUSES,
};
